set et
set nowrap
set nowb
set nu
set si
set sm
set sts=4
set sw=4
set ts=4
filetype plugin indent on

let g:mapleader = ","

nmap <Leader>C :enew<CR>
nmap <Leader>bq :bp <BAR> bd #<CR>
nmap <Leader>" :split<CR>
nmap <Leader>% :vsplit<CR>

call plug#begin()
Plug 'preservim/nerdtree' | Plug 'ryanoasis/vim-devicons' | Plug 'tiagofumo/vim-nerdtree-syntax-highlight'
Plug 'vim-airline/vim-airline'
Plug 'jeetsukumaran/vim-buffergator'

Plug 'Yggdroot/indentLine'

Plug 'dracula/vim', { 'as': 'dracula' }
call plug#end()

let g:NERDTreeQuitOnOpen = 1
let g:NERDTreeIgnore = [
\]
autocmd BufEnter * lcd %:p:h
map <Leader>t <ESC>:NERDTreeToggle<CR>

let g:airline#extensions#tabline#enabled = 1

let g:buffergator_viewport_split_policy = "R"
let g:buffergator_suppress_keymaps = 1
nmap <leader>bl :BuffergatorOpen<cr>
nmap <leader>h :BuffergatorMruCyclePrev<cr>
nmap <leader>l :BuffergatorMruCycleNext<cr>

colorscheme dracula
