export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="dracula"
zstyle ":omz:update" mode auto

plugins=(
    git
    python
    ruby
    vi-mode
)

source $ZSH/oh-my-zsh.sh

alias vi="vim"
alias vid="vim"

alias l="ls"
alias ll="ls -l"
alias la="ls -al"

alias cl="clear"

alias python=python3
alias pip=pip3
